---
- name: Get MAC address table
  hosts: gns3_core, gns3_access
  gather_facts: false


  tasks:
    - name: get  mac address table
      raw: "show mac address-table"
      register: showMAC
    - debug: var=showMAC.stdout_lines

