---
- name: Deploy HSRP
  connection: local
  gather_facts: False
  hosts: SW1

  tasks:
    - name: Configure HSRP on SW1
      ios_config:
        provider:
          authorize: yes
          auth_pass: kao123
          timeout: 60
        parents: "interface vlan {{ item.interface }}"
        lines:
          - "ip address {{ item.ip_address }} {{ item.netmask }}"
          - "standby 1 ip {{ item.standby_ip}}"
          - "standby 1 priority {{ item.priority }}"
          - standby 1 preempt
        after:
          - no shutdown
          - do wr
      with_items:
        - { interface : 10, ip_address : 192.168.10.1, netmask : 255.255.255.0, standby_ip : 192.168.10.10, priority : 200 }
        - { interface : 20, ip_address : 192.168.20.1, netmask : 255.255.255.0, standby_ip : 192.168.20.10, priority : 200 }
        - { interface : 30, ip_address : 192.168.30.1, netmask : 255.255.255.0, standby_ip : 192.168.30.10, priority : 160 }

    - name: Configure STP on SW1
      ios_config:
        provider:
          authorize: yes
          auth_pass: kao123
          timeout: 60
        lines:
          - ip routing
          - spanning-tree mode rapid-pvst
          - spanning-tree vlan 10,20 root primary
          - do wr

- name: HSRP AND STP
  connection: local
  gather_facts: False
  hosts: SW2

  tasks:
    - name: Configure HSRP on SW2
      ios_config:
        provider:
          authorize: yes
          auth_pass: kao123
          timeout: 60
        parents: "interface vlan {{ item.interface }}"
        lines:
          - "ip address {{ item.ip_address }} {{ item.netmask }}"
          - "standby 1 ip {{ item.standby_ip}}"
          - "standby 1 priority {{ item.priority }}"
          - standby 1 preempt
        after:
          - no shutdown
          - do wr
      with_items:
        - { interface : 10, ip_address : 192.168.10.2, netmask : 255.255.255.0, standby_ip : 192.168.10.10, priority : 160 }
        - { interface : 20, ip_address : 192.168.20.2, netmask : 255.255.255.0, standby_ip : 192.168.20.10, priority : 160 }
        - { interface : 30, ip_address : 192.168.30.2, netmask : 255.255.255.0, standby_ip : 192.168.30.10, priority : 200 }

    - name: Configure STP on SW2
      ios_config:
        provider:
          authorize: yes
          auth_pass: kao123
          timeout: 60
        lines:
          - ip routing
          - spanning-tree mode rapid-pvst
          - spanning-tree vlan 30 root primary
